- name: meta
  label: 'META informace'
  form:
  - component: input
    label: 'Titulek v META'
    name: 'title'
    rules: 'required'
  - component: textarea
    label: 'Popisek v META'
    name: 'desc'
    rules: 'required'
- name: hero
  label: 'Hlavni prispevek'
  form:
    - name: background
      label: 'pozadi'
      component: input
    - name: title
      component: input
      label: 'Hlavní titulek'
    - name: subtitle
      component: input
      label: 'Podtitul'
    - name: content
      label: 'obsah'
      component: textarea
- name: warning
  label: 'Disclaimer'
  form:
    - name: content
      component: textarea
